services:
  java_apps:
    container_name: java_apps
    image: java-app:1.0.0
    build:
      context: ./AndamiosBackend/
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - "465:465"
      - "587:587"
      - "8090:8090"
    expose:
      - 8090
      - 465
      - 587
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://vps-3897990-x.dattaweb.com:3306/sistemaandamios?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=andamiero
      - SPRING_DATASOURCE_PASSWORD=andamios..&&Cardon&&..&&sri&&..&&0803
    networks:
      - app_network

  flet_app:
    container_name: flet_cursos
    image: flet-app:1.0.0
    build:
      context: ./PROYECTO_FLET/
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - FLET_SERVER_PORT=8095  # Cambiado para evitar conflicto con java_apps
      - FLET_FORCE_WEB_VIEW=true
      - FLET_BASE_URL=/cursos
    volumes:
      - ./PROYECTO_FLET/config:/app/config:ro
    expose:
      - 8095
    networks:
      - app_network
    depends_on:
      - java_apps
### Angular Apps
  angular_apps:
    container_name: angular_apps
    image: angular-app:1.0.0
    build:
      context: ./AndamiosFrontEnd/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "443:443"
      - '80:80'
    volumes:
      - /etc/letsencrypt/live/app-sanrafael.cl/fullchain.pem:/etc/letsencrypt/live/app-sanrafael.cl/fullchain.pem
      - /etc/letsencrypt/live/app-sanrafael.cl/privkey.pem:/etc/letsencrypt/live/app-sanrafael.cl/privkey.pem
      - /etc/letsencrypt/live/app-sanrafael.cl/chain.pem:/etc/letsencrypt/live/app-sanrafael.cl/chain.pem
      - /etc/letsencrypt/live/app-sanrafael.cl/cert.pem:/etc/letsencrypt/live/app-sanrafael.cl/cert.pem
      - /etc/letsencrypt/live/app-sanrafael.cl/README:/etc/letsencrypt/live/app-sanrafael.cl/README
      - ./AndamiosFrontEnd/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 433
    depends_on:
      - java_apps
      - flet_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge